services:
  botintranetcicpc:
    env_file: 
      - .env
    container_name: botIntranetCICPC
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - .:/app
    ports:
      - $DOCKER_PORT:$LOCAL_PORT
    expose:
      - $LOCAL_PORT
    extra_hosts:
      - "host.docker.internal:host-gateway"